src/app.ts
src/commands/index.ts
src/commands/prune.ts
src/commands/uznanipredmetu.ts
src/commands/whois.ts

feat: Add permissions and linting

---

package-lock.json
package.json
src/commands/index.ts
src/commands/verify.ts
src/utils/index.ts
src/utils/scrapeConfirmationStudies.ts
src/utils/scrapeThesis.ts
tests/verify.test.ts

This PR creates verification command and tests for it.
To run verification command in bot use following:
```
/verify <full-link-to-confirmation-muni> <full-link-to-space>
```
where link to confirmation looks like:
`https://is.muni.cz/confirmation-of-studies/owcvx48n?lang=en` or `https://is.muni.cz/confirmation-of-studies/owcvx48n`
and link to dspace looks like:
`https://dspace.vutbr.cz/handle/11012/192124`

Add verify

---

.dockerignore
.github/actions/deploy-app/action.yaml
.github/actions/prepare-image/action.yaml
.github/workflows/deploy-app.yaml
.gitignore
Dockerfile
LICENSE
README.md
package.json
src/commands/verify.ts
src/utils/User.ts
src/utils/assignRole.ts
src/utils/index.ts
src/utils/scrapeConfirmationStudies.ts
src/utils/scrapeThesis.ts
tests/verify.test.ts

Add logging

---

.github/actions/prepare-image/action.yaml

fix: prepare-image action

---

README.md

fix: Fix badges in readme

---

README.md

feat: Add image to README

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/question.yaml
.github/workflows/react-new-pr.yaml

Add codeowners templates

---

.github/actions/prepare-image/action.yaml
Dockerfile

Since x86 machines had not enough resources we had to migrate to arm

feat: Migrate from X86 to ARM

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/question.yaml
.github/pull_request_template.md
.github/workflows/react-new-pr.yaml

Adds PR template and fixes labels in issue templates

feat: Add PR template

---

package-lock.json
package.json

Tiny update of package.json and package-lock.json to reflect current state of repository.

fix: update package.json after repo migration

---

renovate.json

Updates renovate.json so taht we have less opened PRs from renovate bot

feat: Group up all dependecies

---

renovate.json

fix: Exclude discordjs from updates

---

.github/actions/validate-user/action.yaml
.github/workflows/new-pr-created.yaml
renovate.json

feat: Add .github to exluded directories

---

Dockerfile
package-lock.json
package.json

Image wasn't building because of some issue with nodemon, not sure 100 % what is causing that but, simpliest fix is to have nodemon optional since we don't need it in production and you can work with it in dev as normal

fix: Fix issue that image wasn't building

---

.github/actions/prepare-image/action.yaml

Fix issue when image was not being pushed to dockerhub

fix: Fix issue with ARM pipeline

---

package-lock.json
package.json
src/app.ts
src/buttons/addChannelButton.ts
src/commands/channelmanagement.ts
src/commands/restart.ts
src/listeners/interactionListener.ts
src/selects/channelSelect.ts
src/utils/index.ts
src/utils/parseCustomId.ts
src/utils/setupSubjectChannels.ts

https://github.com/OqixDevs/OqixTS/issues/35
Fixes channel select crashing when a category had more than 25 channels

Fix channel select not working above 25 channels

---

src/commands/edit.ts
src/commands/index.ts

Command to edit messages sent by bot. Only affect text content, embeds and attachments are left as is.
`/edit content: <new content> message: <message id> [channel: <channel id>]`

Command to edit bot messages

---

src/app.ts
src/listeners/index.ts
src/listeners/pinVoteListener.ts

Feature adds option to pin messages by users themselves using the 📌 emoji reaction enough times.

Add message pinning by voting with reactions

---

.pre-commit-config.yaml
package-lock.json
package.json
src/commands/whoami.ts

Update prettier since new major version seems to have changed formatting little bit

chore: update prettier

---

.github/actions/deploy-app/action.yaml
src/listeners/interactionListener.ts
src/selects/channelSelect.ts
src/utils/setupSubjectChannels.ts

This PR fixes various deprecation warnings and also updates restart policy for the docker image.

chore: fix deprecation issues and CI restart

---

.github/actions/deploy-app/action.yaml
.github/actions/restart-app/action.yaml
.github/workflows/deploy-app.yaml
.github/workflows/restart-app.yaml

This PR adds forgotten database variables

fix: Add database connection variable to actions

---

src/commands/verify.ts
src/utils/assignRole.ts
src/utils/scrapeThesis.ts

Links on the dspace website changed and also layout of the actual website changed. This PR fixes issues caused by that

fix: Fix scraping issues caused by recent change of dspace site

---

src/commands/review.ts
src/commands/verify.ts
src/utils/assignRole.ts
src/utils/scrapeConfirmationStudies.ts
src/utils/scrapeThesis.ts

This PR fixes recent changes to path on MUNI confirmation page. As a second commit it also adds basic logging to app to make future debugging easier

Fix confirmation scraping muni and log issues

---

src/commands/graduate.ts
src/commands/index.ts

Resolves https://github.com/OqixDevs/OqixTS/issues/108
This feature is adds an option for verified users to permanently self-assign role 'graduate'.

feat: Add option to self-assign graduate role

---

.pre-commit-config.yaml
src/commands/verify.ts
src/utils/scrapeThesis.ts

This PR fixes new link to dspace (hdl.handle.net) and also changes help to be more clear on UUID part

fix: Add additional option for links to dspace

---

Dockerfile

fix: Bump dockerfile
